"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 3, 3 ]
sort_by        = "natural"
show_hidden    = true
linemode       = "size_and_mtime"

[opener]
edit = [
	{ run = '$EDITOR "$@"', desc = '$EDITOR', block = true, for = "unix" },
	{ run = 'sudo $EDITOR "$@"', desc = 'sudo $EDITOR', block = true, for = "unix" }
]

[input]
cursor_blink = true

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
