# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "user", color = "(CN)"}
hostname  = {icon = " ", name = "hostname", color = "(YW)"}
sep_system = "SEPARATOR"
distro    = {icon = " ", name = "distro", color = "(GN)"}
kernel    = {icon = " ", name = "kernel", color = "(MA)"}
uptime    = {icon = " ", name = "uptime", color = "(BE)"}
sep_desktop = "SEPARATOR"
desktop   = {icon = " ", name = "desktop", color = "(CN)"}
terminal  = {icon = " ", name = "term", color = "(YW)"}
shell     = {icon = " ", name = "shell", color = "(GN)"}
packages  = {icon = " ", name = "packages", color = "(RD)"}  # WARNING: Resource Intensive
sep_hardware = "SEPARATOR"
cpu       = {icon = " ", name = "cpu", color = "(BE)"}
gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}       # WARNING: Resource Intensive
disk_0    = {icon = " ", name = "disk", color = "(GN)"}
memory    = {icon = " ", name = "memory", color = "(YW)"}
# battery    = {icon = " ", name = "battery", color = "(GN)"}
sep_color = "SEPARATOR"
# weather   = {icon = " ", name = "weather", color = "(BE)"} # Requires curl and an emoji font. | WARNING: Resource Intensive
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "dashed"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "!DT!"
font   = "ogre"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path   = "/home/steinardth/Pictures/Vagabond-soldier-blue.png" # Please only use absolute paths.
scale  = 18
margin = [2, 2, 3,]
